version: '3'

services:
  web:
    image: vsplate/php7-apache-ghostscript9.23:latest
    volumes:
      - ./docker-php.conf:/etc/apache2/conf-enabled/docker-php.conf
      - ./html:/var/www/html/
    ports:
      - "80:80"
